In [2]:

import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],2)
        self.weights2   = np.random.rand(2,1)
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":

    print("result")
    X = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(15000):
        nn.feedforward()
        nn.backprop()

    print(nn.output)
    print()
    
    x = np.array([0, 0])
    w1 = np.asarray(nn.weights1)
    w2 = np.asarray(nn.weights2)
    h = sigmoid(np.matmul(x,w1))
    logit = np.matmul(h,w2)
    y = sigmoid(logit)
    print(y)
    
    print()
    print(w1)
    print(w2)
    
    

result
[[0.01524864]
 [0.96183985]
 [0.96183986]
 [0.05113358]]

[0.01524792]

[[8.3530503  0.94692905]
 [8.35430805 0.94693026]]
[[ 33.06181873]
 [-41.39771183]]
